name: Deploy to VPS

on:
  push:
    branches:
      - main   # Chạy khi push lên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          script: |
            # Tạo folder nếu chưa tồn tại và di chuyển vào đó
            mkdir -p /var/www/zantraglobal.com
            cd /var/www/zantraglobal.com

            # Kiểm tra git repo
            if [ ! -d ".git" ]; then
              git clone https://x-access-token:${{ secrets.PAT }}@github.com/jakediep1902/zantraglobal.com.git .
            else
              git reset --hard
              git pull origin main
            fi

            # Phân quyền cho web server
            chown -R www-data:www-data /var/www/zantraglobal.com
            chmod -R 755 /var/www/zantraglobal.com

            # Optional: reload Nginx nếu cần
            # sudo systemctl reload nginx
